name: Task Manager Bot Testing Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Utilizando Python versión 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Ejecución de tests de funcionalidades
        run: python test.py